In [9]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [15]:
R = np.array(revenue)
C = np.array(expenses)

In [103]:
Profit = (R - C)

In [105]:
Profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [107]:
Profit_after_tax = Profit*(1-0.3)

In [109]:
Profit_after_tax

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [111]:
Profit_margin = Profit_after_tax/R*100

In [113]:
Profit_margin

array([ 12.11616324,  17.58995643, -30.13969838, -22.23352417,
        -5.21109615,  62.74388559,  49.99343266,  28.27619856,
        22.60844884, -10.89749207,   4.30951365,  52.74680403])

In [65]:
Good_month = Profit_after_tax > np.mean(Profit_after_tax)

In [67]:
Good_month

array([ True, False, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [69]:
Bad_month = Profit_after_tax < np.mean(Profit_after_tax)

In [71]:
Bad_month

array([False,  True,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [73]:
Best_month = Profit_after_tax == np.max(Profit_after_tax)

In [75]:
Best_month

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [77]:
Worst_month = Profit_after_tax == np.min(Profit_after_tax)

In [79]:
Worst_month

array([False, False,  True, False, False, False, False, False, False,
       False, False, False])

In [135]:
#Rounding
R1000 = np.round(R/1000,0)
C1000 = np.round(C/1000,0)
Profit1000 = np.round(Profit/1000,0)
Profit_after_tax1000 = np.round(Profit_after_tax/1000,0)
Profit_margin_round = np.round(Profit_margin,2)

In [131]:
print("Revenue:")
print(R1000)
print("Expenses:")
print(C1000)
print("Profit:")
print(Profit1000)
print("Profit after tax:")
print(Profit_after_tax1000)
print("Profit margin:")
print(Profit_margin_round)
print("Good months:")
print(Good_month)
print("Bad months:")
print(Bad_month)
print("Best months:")
print(Best_month)
print("Worst months:")
print(Worst_month)


Revenue:
[15.0, 8.0, 9.0, 9.0, 8.0, 8.0, 11.0, 10.0, 10.0, 14.0, 11.0, 15.0]
Expenses:
[12.  6. 12. 12.  9.  1.  3.  6.  7. 17. 10.  4.]
Profit:
[ 3.  2. -4. -3. -1.  7.  8.  4.  3. -2.  1. 12.]
Profit after tax:
[ 2.  1. -3. -2. -0.  5.  6.  3.  2. -2.  0.  8.]
Profit margin:
[ 12.12  17.59 -30.14 -22.23  -5.21  62.74  49.99  28.28  22.61 -10.9
   4.31  52.75]
Good months:
[ True False False False False  True  True  True  True False False  True]
Bad months:
[False  True  True  True  True False False False False  True  True False]
Best months:
[False False False False False False False False False False False  True]
Worst months:
[False False  True False False False False False False False False False]
